### ISSUE TITLE
Make TypeScript type definitions from application schema work with Imports from Prisma

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-import#93]
@nickluger commented on [Fri Feb 23 2018](https://github.com/graphcool/prisma/issues/1968)

1. Define your app schema, and use imports from `prisma.graphql` in it:

```graphql
# import DateTime from "./generated/prisma.graphql"

type Foo{
    bar: DateTime
}
```

2. Run 
```shell
yarn graphql prepare -p app --output src/generated -g binding-ts --bindings --bundle --save
```
or just `yarn graphql prepare` if you have a proper definition in your `graphqlconfig.yml`
Mine looks like this
```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      prepare-binding:
        output: src/generated/app.ts
        generator: binding-ts
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts

```

Result:

```
✖ Generating bindings for project app...
Type "DateTime" not found in document.
```

**Comment by schickling** [comment]
Hi @nickluger, I've just tried to reproduce this problem locally but it's working for me. Can you provide a repo with a minimal reproduction? Ideally with pinned versions.

**Comment by nickluger** [comment]
Was busy, but there you go: https://github.com/nickluger/graphql-import-from-prisma

**Comment by schickling** [comment]
@kbrandwijk from looking into this, the problem seems to be in the `prepare-binding` CLI part which right now doesn't seem to support `graphql-import` (see here in `src/schema.graphql`).

Can you push a fix for this? This should solve @nickluger's problem. :)

**Comment by schickling** [comment]
@nickluger this should be fixed by installing `v2.15.8` of the `graphql-cli`.

I was also talking to @kbrandwijk via Slack who suggested to use `prepare-bundle` to optimize the build speed. Can you please elaborate a bit @kbrandwijk?

**Comment by kbrandwijk** [comment]
@nickluger Even though the latest `graphql-cli` release will also run `prepare-binding` on schemas with import statements, `prepare-binding` is actually optimized to run _after_ `prepare-bundle`.
You can achieve this by adding `prepare-bundle` to your `.graphqlconfig` like this:
```yaml
app:
    schemaPath: "src/schema.graphql"
    extensions:
      prepare-bundle: src/generated/app.graphql
      prepare-binding:
        output: src/generated/app.ts
        generator: binding-ts
      endpoints:
        default: "http://localhost:4000"
```

Now you can use the schema with imports already processed (`src/generated/app.graphql`) directly. An additional benefit is that the bundled schema will actually exist as a physical file, instead of in-memory only, so it's easier to view/debug.
